(global-set-key (kbd "<C-s-268632070>") 'toggle-frame-fullscreen)
(global-set-key (kbd "s-=") 'text-scale-increase)
(global-set-key (kbd "s--") 'text-scale-decrease)
(global-set-key (kbd "M-s-∑") 'toggle-truncate-lines)
(global-set-key (kbd "C-x \\") 'align-regexp)
(global-set-key (kbd "C-M-\\") 'avdg-indent-region-or-buffer)
(global-set-key (kbd "s-d") 'avdg-duplicate-line)
(global-set-key [remap move-beginning-of-line] 'avdg-smarter-move-beginning-of-line)
(global-set-key (kbd "s-§") 'avdg-toggle-eshell-buffer)
(global-set-key (kbd "M-o") 'avdg-open-newline-below)
(global-set-key (kbd "M-O") 'avdg-open-newline-above)
(global-set-key (kbd "s-<up>") 'avdg-move-text-up)
(global-set-key (kbd "s-<down>") 'avdg-move-text-down)
(define-key dired-mode-map "e" (lambda () (interactive) (eshell t)))
(provide 'ag-keys)
