language: python

python:
  # TOOD: add support for one python3 version. The problem here is Vim: we need to install a version of vim that
  # has py3, but not py2. I could not figure this out so far.
  - 2.7
before_script:
  # Clone the dependent plugins we want to use.
  - ./test_all.py --clone-plugins
  # Install tmux (> 1.8) and vim. 
  - sudo add-apt-repository ppa:kalakris/tmux -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y tmux vim-gnome
  # Start the testing session.
  - tmux new -d -s vim
  - vim --version
script: ./test_all.py -v --plugins --interface tmux --session vim
