install ack
install ant
install apple-gcc42
install asciidoc
install autoconf
install automake
install boost
install cmake
install ctags
install docbook
install docbook-xsl
install elixir
install epubcheck
install erlang-r16
install figlet
install freetype
install gdbm
install gettext
install gh
install git
install gnu-getopt
install go
install graphviz
install highlight
install hub
install imagemagick
install jpeg
install jsmin
install libevent
install libpng
install libtool
install libyaml
install lua
install maven
install mercurial
install mutt
install mysql
install ngrep
install node
install openssl
install ossp-uuid
install pcre
install phantomjs
install pkg-config
install postgresql
install python
install qt
install rbenv
install rbenv-vars
install readline
install reattach-to-user-namespace
install redis
install ruby-build
install s3cmd
install sl
install sqlite
install tmux
install tokyo-cabinet
install tree
install vim
install watch
install wemux
install wget
install wkhtmltopdf
install xmlto
install zsh
