install ack
install ant
install apple-gcc42
install asciidoc
install autoconf
install automake
install bison
install boost
install cmake
install ctags
install docbook
install docbook-xsl
install emacs
install epubcheck
install erlang-r16
install figlet
install freetype
install gdbm
install gettext
install gh
install git
install glib
install gnu-getopt
install go
install graphviz
install highlight
install hub
install icu4c
install imagemagick
install irssi
install jpeg
install jq
install jsmin
install leiningen
install libevent
install libffi
install libpng
install libtiff
install libtool
install libyaml
install lsof
install lua
install mercurial
install mysql
install ngrep
install node
install openssl
install ossp-uuid
install pcre
install phantomjs
install pkg-config
install postgresql
install python
install qt
install rbenv
install rbenv-vars
install readline
install reattach-to-user-namespace
install redis
install ruby-build
install s3cmd
install sl
install sqlite
install tmux
install tokyo-cabinet
install tree
install unixodbc
install vim
install watch
install wemux
install wget
install wkhtmltopdf
install wxmac
install zsh
