" Deal witg multiple buffers better
set hidden

" Automatically update changes to a file when receiving focus
set autoread

" Keep a longer history
set history=100

" Make file/command completion useful
set wildmenu
set wildmode=list:longest

" Fast editing and updating of the .vimrc (reloads on save)
map <Leader>e :e! ~/.vimrc<cr>
autocmd! bufwritepost vimrc source ~/.vimrc

" Do not emulate vi
set nocompatible

" Intuitive Backspace
set bs=indent,eol,start

" Filetype detection
filetype plugin indent on

" Line wrapping
set nowrap
set linebreak

" Syntax highlighting
syntax on
set showmatch " matching braces
set background=dark
colorscheme ir_black

" Auto-reading on file changes
set autoread

" Status line
set showcmd
set ruler
set nu

" Scrollbars
set sidescrolloff=2
set numberwidth=4

" Maintain more context around the cursor
set scrolloff=3

" Do not keep backup files. We use source control anyway.
set nobackup
set nowritebackup
set noswapfile

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Set terminal title
set title

" Hide search highlighting
map <Leader>h :set invhls <CR>

" Quickly toggle NERDTree
nmap <Leader>n :NERDTreeToggle<CR>

" Indenting
set softtabstop=4
set tabstop=4
set shiftwidth=4
set expandtab
set ai " Automatically set the indent of a new line
set si " Smart indent

" Use 2 spaces for tabs in ruby and associated langs
autocmd Filetype ruby,yaml,rake,rb setlocal ts=2 sw=2 expandtab

" Run ruby files using \r
autocmd Filetype ruby,rb nmap <Leader>r :!ruby %<CR>

" Open HTML files in Safari using \r
autocmd Filetype html nmap <Leader>r :!open -a Safari %<CR>

" Enable soft-wrapping for text files
autocmd FileType text,markdown,html,xhtml,eruby setlocal wrap linebreak nolist

" Custom SVN location for vcscommand plugin
let VCSCommandSVNExec="/opt/subversion/bin/svn"

" Toggle word wrap with \w
map <Leader>w :set nowrap!<CR>

" Treat .less files as .css files
au BufNewFile,BufRead *.less setfiletype css

" Always open new windows below/to the right
set sb
set spr

" Use Ack
if executable("ack")
    set grepprg=ack\ -H\ --nogroup\ --nocolor\ --ignore-dir=tmp\ --ignore-dir=coverage
endif

" Unmap arrow keys to force learning hjkl
map <Left> \
map <Right> \
map <Up> \
map <Down> \

" Fuzzyfinder plugin
try
    call fuf#defineLaunchCommand('FufCWD', 'file', 'fnamemodify(getcwd(), ''%:p:h'')')
    map <leader>t :FufCWD **/<CR>
catch
endtry

" Customizations for the surround plugin
" PHP
" Use p to get php tags
autocmd FileType php let b:surround_112 = "<?php \r ?>"     " p
autocmd FileType php let b:surround_61 = "<?php echo \r ?>"     " =
