(setq use-package-verbose t)

(require 'ag-ag)
(require 'ag-projectile)
(require 'ag-helm)
(require 'ag-magit)
(require 'ag-paredit)
(require 'ag-ruby)
(require 'ag-company)
(require 'ag-css)
(require 'ag-expand-region)
(require 'ag-javascript)
(require 'ag-multiple-cursors)
(require 'ag-elixir)
(require 'ag-elm)
(require 'ag-web-mode)
(require 'ag-flycheck)
(require 'ag-yasnippet)
(require 'ag-org)
(require 'ag-markdown)
(require 'ag-asciidoc)
(require 'ag-clojure)
(require 'ag-avy)
(require 'ag-smartparens)
