#!/bin/bash

export DIRENV_LOG_FORMAT=""

layout_postgres() {
  export PGDATA="$(direnv_layout_dir)/postgres"
  export PGHOST="$PGDATA"

  if [[ ! -d "$PGDATA" ]]; then
    initdb
    cat >> "$PGDATA/postgresql.conf" <<-EOF
listen_addresses = ''
unix_socket_directories = '$PGHOST'
EOF
    echo "CREATE DATABASE $PGDATABASE;" | postgres --single -E postgres
  fi
}

add_extra_vimrc() {
  local extravim="$(find_up .vimrc)"
  if [ -n "$extravim" ]; then
    echo "Adding extra .vimrc: ${extravim}"
    path_add EXTRA_VIM $extravim
  fi
}
