language: python

python:
  - 2.7
  - 3.3
  - 3.4
env:
  - VIM_VERSION="74"

install: sudo ./install_vim.sh "${VIM_VERSION}" "$(python --version 2>&1)"

before_script:
  - tmux new -d -s vim

script: ./test_all.py -v --plugins --session vim
